```{r NULL MODELS}
null_model1 = SDMPlay:::null.model(xy = data[,2:3],predictors = envi_data, type = 1, algorithm ="brt", nb = 1000, unique.data = T, same = T, nb.rep = 5, tc = 5,
lr = 0.001, bf = 0.75)

null_model2 = SDMPlay:::null.model(xy = data[,2:3],predictors = envi_data, type = 2, algorithm ="brt", nb = 1000, unique.data = T, same = T, nb.rep = 5, tc = 5,
lr = 0.001, bf = 0.75)

plot(basemap)
SOplot(null_model1$pred.mean, col = palettemulticolor)

plot(basemap)
SOplot(null_model2$pred.mean, col = palettemulticolor)
```

```{r RANDOM CROSS-VALIDATION - LOOP}
library(SDMPlay)
setwd("/Users/charlieplasman/Desktop")

# Choose the occurrence data (random/KDE)
data <- HSMtable_KDE

n_repeats <- 5 # Number of repetitions
model_outputs <- vector("list", n_repeats)  # List to store the model outputs

for (i in 1:n_repeats) {
  # Choose the occurrence data (random/KDE)
  HSMtable_KDE= SDMPlay:::SDMtab(xydata=spat_occ, predictors=stack_linear, 
                                 unique.data=TRUE,same=TRUE, KDE=KDE_layer)
  data = HSMtable_KDE
  model_output <- SDMPlay:::compute.brt(x = data, proj.predictors = envi_data,
                              tc = 5, lr = 0.0005, bf = 0.75, n.trees = 500, 
                              step.size = 500, n.folds = 5)
  model_outputs[[i]] <- model_output
}

# Initialize an empty list to store the raster predictions
raster_predictions <- vector("list", length(model_outputs))

# Extract raster predictions from each model output
for (i in 1:length(model_outputs)) {
  raster_predictions[[i]] <- model_outputs[[i]]$raster.prediction
}

# Create the stacked raster
stack.pred <- stack(raster_predictions)

# Calculate the average prediction
average_pred <- calc(stack.pred, mean)

plot(basemap)
SOplot(average_pred, col = hcl.colors(80, "Viridis"))
```

```{r}
crumb = model_outputs
crumb2 = model_outputs
crumb = model_outputs[1:5]
model_outputs[6:10] = crumb2[1:5]
plot(basemap)
SOplot(average_pred, col = hcl.colors(80, "Viridis"))
```

```{r SPATIAL CROSS-VALIDATION (CLOCK 2) - LOOP}
library(SDMPlay)
setwd("~/Desktop/MeÌmoire /Personal data")

n_repeats <- 10  # Number of repetitions
model_outputs <- vector("list", n_repeats)  # List to store the model outputs

for (i in 1:n_repeats) {
  # Choose the occurrence data (random/KDE)
  HSMtable_KDE= SDMPlay:::SDMtab(xydata=spat_occ, predictors=stack_linear, 
                                 unique.data=TRUE,same=TRUE, KDE=KDE_layer)
  data = HSMtable_KDE
  # Create replicates with different partitioning
  idP <- which(data$id == 1)
  partition_function <- SDMPlay:::clock2(data[idP, c("longitude", "latitude")], data[-idP, c("longitude", "latitude")])
  MyFold <- rep(NA, nrow(data))
  MyFold[idP] <- partition_function$occ.grp
  MyFold[-idP] <- partition_function$bg.coords.grp
  {
    plot(basemap)
    SOplot(data[, c("longitude", "latitude")],
           col = c("orange", "darkblue")[as.factor(MyFold)],
           pch = 20)
    SOleg(col = c("orange", "darkblue"), position = "topright",
          tlabs = c("training", "test"), type = "discrete")
  }
  
  model_output <- SDMPlay:::compute.brt(x = data, proj.predictors = envi_data,
                              tc = 2, lr = 0.001, bf = 0.75, 
                              n.trees = 500, step.size = 500,
                              n.folds = 2,
                              fold.vector = MyFold)
  model_outputs[[i]] <- model_output
}

# Initialize an empty list to store the raster predictions
raster_predictions <- vector("list", length(model_outputs))

# Extract raster predictions from each model output
for (i in 1:length(model_outputs)) {
  raster_predictions[[i]] <- model_outputs[[i]]$raster.prediction
}

# Create the stacked raster
stack.pred <- stack(raster_predictions)

# Calculate the average prediction
average_pred <- calc(stack.pred, mean)

plot(basemap)
SOplot(average_pred, col = hcl.colors(80, "Viridis"))

#SOleg(x = runif(100), position = "bottomleft", col = hcl.colors(80, "Viridis"),
        #breaks = c(0.2, 0.4, 0.6, 0.8), trim = -45,
        #rnd = 1, type = "continuous")
```

```{r SAVE}
library(ncdf4)
library(raster)
dir = "/Users/charlieplasman/Desktop"
writeRaster(average_pred, filename = file.path(dir, "OMA_PRED.tif"), format="GTiff", overwrite = T)

setwd("/Users/charlieplasman/Desktop")

test = raster("CRAN_PRED.tif")
test2 = raster( "CHANNI_PRED.tif")
plot(basemap)
SOplot(test, col = hcl.colors(80, "Viridis"))
plot(basemap)
SOplot(test2)
```